### PR TITLE
Fix serializing user name

### LINKED ISSUE #6: Presto User Header is unnecessarily serialized
Value part for `hidden args` is serialized. Here, I think it should be `st.user = arg.Value.(string)` cause `s` value is serialized value and user name should not be serialized (else input name would be  `'Amy'`  and not `Amy` like image below ).
- https://github.com/prestosql/presto-go-client/blob/master/presto/presto.go#L568

### Test

``` go
_, err = db.Query("SELECT 2", sql.Named(PrestoUserHeader, string("Amy")))
```

#### Before : Serialized
image

#### After : Not serialized
image

### PR DESCRIPTION
**Pull request by Chaho12**
Issue related to https://github.com/prestosql/presto-go-client/issues/6 where hidden args should not be serialized. 

### before
image

### after

image

Fixes #6

### CODE REVIEW

**Comment by losipiuk** [comment]
@cla-bot check

**Comment by Chaho12** [comment]
@ebyhr 
Unfortunately, I can't add a test case because there is no callback mechanism or sth similar in the code as of now.
In order to test, i need to run the query like `rows, err := db.Query("SELECT 2", sql.Named(PrestoUserHeader, string("TestSample")))` but `rows` only has column fields/types and data.

**Comment by Chaho12** [comment]
@ebyhr Thx for message in slack.

As you said, I've got test case ready, but this test code fails executing query until another BUG is fixed at the following PR
- https://github.com/prestosql/presto-go-client/pull/5 
- works well in my local code where I fixed the bug

``` go
func TestUser(t *testing.T) {
	c := &Config{
		PrestoURI:         "http://foobar@localhost:8080",
		SessionProperties: map[string]string{"query_priority": "1"},
	}
	dsn, err := c.FormatDSN()
	if err != nil {
		t.Fatal(err)
	}

	db, err := sql.Open("presto", dsn)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	rows, err := db.Query("SELECT current_user", sql.Named("X-Presto-User", string("TestUser")))
	if err != nil {
		t.Fatal("Failed executing query", err.Error())
	}

	if rows != nil {
		for rows.Next() {
			var ts string
			err = rows.Scan(&ts)
			if err != nil {
				t.Fatal("Failed scanning query result", err.Error())
			}
			want := "TestUser"
			if ts != want {
				t.Fatal("Expected value does not equal result value : ", ts, " != ", want)
			}
		}
	}
}
```

### before

image

### after

image

**Comment by Chaho12** [comment]
@ebyhr added test code :)

File: presto/presto_test.go [hunk 1]
```diff
@@ -238,6 +238,41 @@ func TestQueryWithJustUserHeader(t *testing.T) {
 	}
 }
 
+func TestQueryForUsername(t *testing.T) {
```
Comment (losipiuk) [inline presto/presto_test.go:241]: I guess you can just change the `TestQueryWithJustUserHeader` to query for `current_user` and have and rename it to `TestQueryForUsername`; but having two tests is fine too.
Please squash two commits together.

Comment (Chaho12) [reply presto/presto_test.go:206]: Two tests seems to overlap each other, so I got rid of `TestQueryWithJustUserHeader` because `TestQueryForUsername` tests with just user header.

**Review by losipiuk — APPROVED** [review]

**Comment by losipiuk** [comment]
/lgtm
/approve
Thanks!
